[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.7.0"
rand_core = "0.6.4"

[dev-dependencies]
embedded-graphics-simulator = "0.3.0"
rand = "0.8.5"
